### ISSUE TITLE
Docksal.io Update to Docker Link/Version

### ISSUE THREAD

**Issue by willykaram** [docksal/docksal.io#20]
The Docker link/version in the install instructions should be updated to more recent and likely correct version to minimize the sort of issues people are encountering like this:

https://github.com/docksal/docksal/issues/482

The getting started materials should also likely be updated:

https://docs.docksal.io/getting-started/setup/

**Comment by lmakarov** [comment]
Fixed in 496283bf3d38b263926b7274e390a8f3b4872792
